REM Removing insecure stuff
echo "DISABLING WEAK SERVICES"
dism /online /disable-feature /featurename:IIS-WebServerRole /remove /NoRestart
dism /online /disable-feature /featurename:IIS-WebServer /remove /NoRestart
dism /online /disable-feature /featurename:IIS-CommonHttpFeatures /remove /NoRestart
dism /online /disable-feature /featurename:IIS-HttpErrors /remove /NoRestart
dism /online /disable-feature /featurename:IIS-HttpRedirect /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ApplicationDevelopment /remove /NoRestart
dism /online /disable-feature /featurename:IIS-NetFxExtensibility /remove /NoRestart
dism /online /disable-feature /featurename:IIS-NetFxExtensibility45 /remove /NoRestart
dism /online /disable-feature /featurename:IIS-HealthAndDiagnostics /remove /NoRestart
dism /online /disable-feature /featurename:IIS-HttpLogging /remove /NoRestart
dism /online /disable-feature /featurename:IIS-LoggingLibraries /remove /NoRestart
dism /online /disable-feature /featurename:IIS-RequestMonitor /remove /NoRestart
dism /online /disable-feature /featurename:IIS-HttpTracing /remove /NoRestart
dism /online /disable-feature /featurename:IIS-Security /remove /NoRestart
dism /online /disable-feature /featurename:IIS-URLAuthorization /remove /NoRestart
dism /online /disable-feature /featurename:IIS-RequestFiltering /remove /NoRestart
dism /online /disable-feature /featurename:IIS-IPSecurity /remove /NoRestart
dism /online /disable-feature /featurename:IIS-Performance /remove /NoRestart
dism /online /disable-feature /featurename:IIS-HttpCompressionDynamic /remove /NoRestart
dism /online /disable-feature /featurename:IIS-WebServerManagementTools /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ManagementScriptingTools /remove /NoRestart
dism /online /disable-feature /featurename:IIS-IIS6ManagementCompatibility /remove /NoRestart
dism /online /disable-feature /featurename:IIS-Metabase /remove /NoRestart
dism /online /disable-feature /featurename:IIS-HostableWebCore /remove /NoRestart
dism /online /disable-feature /featurename:IIS-StaticContent /remove /NoRestart
dism /online /disable-feature /featurename:IIS-DefaultDocument /remove /NoRestart
dism /online /disable-feature /featurename:IIS-DirectoryBrowsing /remove /NoRestart
dism /online /disable-feature /featurename:IIS-WebDAV /remove /NoRestart
dism /online /disable-feature /featurename:IIS-WebSockets /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ApplicationInit /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ASPNET /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ASPNET45 /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ASP /remove /NoRestart
dism /online /disable-feature /featurename:IIS-CGI /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ISAPIExtensions /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ISAPIFilter /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ServerSideIncludes /remove /NoRestart
dism /online /disable-feature /featurename:IIS-CustomLogging /remove /NoRestart
dism /online /disable-feature /featurename:IIS-BasicAuthentication /remove /NoRestart
dism /online /disable-feature /featurename:IIS-HttpCompressionStatic /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ManagementConsole /remove /NoRestart
dism /online /disable-feature /featurename:IIS-ManagementService /remove /NoRestart
dism /online /disable-feature /featurename:IIS-WMICompatibility /remove /NoRestart
dism /online /disable-feature /featurename:IIS-LegacyScripts /remove /NoRestart
dism /online /disable-feature /featurename:IIS-LegacySnapIn /remove /NoRestart
dism /online /disable-feature /featurename:IIS-FTPServer /remove /NoRestart
dism /online /disable-feature /featurename:IIS-FTPSvc /remove /NoRestart
dism /online /disable-feature /featurename:IIS-FTPExtensibility /remove /NoRestart
dism /online /disable-feature /featurename:TFTP /remove /NoRestart
dism /online /disable-feature /featurename:TelnetClient /remove /NoRestart
dism /online /disable-feature /featurename:TelnetServer /remove /NoRestart
dism /online /disable-feature /featurename:WorkFolders-Client /remove /NoRestart
dism /online /disable-feature /featurename:SMB1Protocol /remove /NoRestart
dism /online /disable-feature /featurename:Xps-Foundation-Xps-Viewer /remove /NoRestart
dism /online /disable-feature /featurename:DirectoryServices-ADAM-Client /remove /NoRestart
dism /online /disable-feature /featurename:Internet-Explorer-Optional-amd64 /remove /NoRestart
dism /online /disable-feature /featurename:Windows-Identity-Foundation /remove /NoRestart
dism /online /disable-feature /featurename:SNMP /remove /NoRestart
PAUSE